### ISSUE TITLE
not enough arguments in call to graphdriver.GetDriver

### ISSUE THREAD

**Issue by vielmetti** [dmcgowan/dsdbench#1]
```
GOPATH=$HOME go test
# dsdbench
./layer_store_util.go:64: not enough arguments in call to graphdriver.GetDriver
FAIL    dsdbench [build failed]
```

environment:

```
# go version
go version go1.6.2 linux/arm64
```

**Comment by dmcgowan** [comment]
Are you building against docker/docker master? Can you try docker 1.12.1 first, I haven't pushed my update to fix this yet.

I was trying to avoid vendoring docker so I could test different versions, but then one of the function interfaces changed :(

**Comment by vielmetti** [comment]
```
# cat /root/src/docker/VERSION
1.12.1
```

What should I set GOPATH to?

**Comment by dmcgowan** [comment]
checkout the version in `$GOPATH/src/github.com/docker/docker` to `1.12.1`, also update `GOPATH=$GOPATH/src/github.com/docker/docker/vendor:$GOPATH` to use the vendor directory.

**Comment by vielmetti** [comment]
I guessed at this patch:

```
diff --git a/layer_store_util.go b/layer_store_util.go
index 128f870..1bdc11b 100644
--- a/layer_store_util.go
+++ b/layer_store_util.go
@@ -61,7 +61,7 @@ func getLayerStore() (layer.Store, error) {
                driverOptions = strings.Split(options, " ")
        }

-       gd, err := graphdriver.GetDriver(driverName, td, driverOptions, nil, nil)
+       gd, err := graphdriver.GetDriver(driverName, td, driverOptions, nil, nil, nil)
        if err != nil {
                return nil, errors.Wrap(err, "failed to get graph driver")
        }
```

which got the tests to "work", though I don't have any confidence in them since I don't know what I added nil to.

The test run gist is here (again, I don't know if the patch is sensible).

https://gist.github.com/423b469d21da240608e4ff13bef047f0

**Comment by dmcgowan** [comment]
Updated to compile with docker master
